### ISSUE TITLE
Save keybinds on config?

### ISSUE THREAD

**Issue by ZellsAlpha** [CodeName-Anti/CrabGame-Cheat#10]
and glassbreaker brokey

**Comment by CodeName-Anti** [comment]
> and glassbreaker brokey

I already know that glassbreaker is broken.

**Comment by ZellsAlpha** [comment]
it seems like it is still broken, it doesn't seem to break anything now

**Comment by CodeName-Anti** [comment]
> it seems like it is still broken, it doesn't seem to break anything now

It only breaks the glass after round start.
