### ISSUE TITLE
2 very good improvements

### ISSUE THREAD

**Issue by ZellsAlpha** [CodeName-Anti/CrabGame-Cheat#15]
Save keybinds on config, and also add infinite punch/speed punch, you can get rid of the punching cooldown, a cheat CGHM 2.9 has it, if you want i can show u it and stuff, its very good

**Comment by ZellsAlpha** [comment]
if u wanna check it/see how they do it here's the link to it 

https://adaf.xyz/adaf/hm/download/cghm/CGHM_v2.9.zip

**Comment by CodeName-Anti** [comment]
> if u wanna check it/see how they do it here's the link to it
> 
> https://adaf.xyz/adaf/hm/download/cghm/CGHM_v2.9.zip

Sorry I cant copy C++ SourceCode to my C# Project, it's just not possible. I will have to try it myself.

**Comment by ZellsAlpha** [comment]
you could also possibly try fixing ESP, sometimes it messes up.

both esp and highlight owner conflict with each other and don't stick per round, its very messed up, and some people get multiple names at once on them

you could also try adding infinite ammo for guns if that's possible, not sure tho

**Comment by CodeName-Anti** [comment]
I think ammo was server sided or something.
