### ISSUE TITLE
owner highlight still doesn't stick per round

### ISSUE THREAD

**Issue by ZellsAlpha** [CodeName-Anti/CrabGame-Cheat#16]
You can have it on, and once a new map gets loaded u have to keep reenabling it for it to show the owner, it doesn't stick properly.
also all cheats are getting instant punch now so its extremely common apparently

**Comment by CodeName-Anti** [comment]
Could you name/link me one that is written in C#?

**Comment by ZellsAlpha** [comment]
idk any that are open src'd i just know a lot of cheats have them

**Comment by ZellsAlpha** [comment]
owner highlight and infinite punch seem to lag the game/ruin fps very badly now

**Comment by CodeName-Anti** [comment]
> idk any that are open src'd i just know a lot of cheats have them

just name or give me the download link to one.

**Comment by ZellsAlpha** [comment]
the only one i had tried other than this one was CGHM
