### ISSUE TITLE
infinity puncher messes up the way the game behaves in some way

### ISSUE THREAD

**Issue by ZellsAlpha** [CodeName-Anti/CrabGame-Cheat#17]
the FPS indicator from steam keeps resetting/ and using rivatuner or other type of shit unhooks and hooks, its weird, also when u enable/disable it it like goes into a different type of window mode, perhaps a weird method of achieving infinite punch?

**Comment by CodeName-Anti** [comment]
This is because I disable Camera shake. I dont edit the window mode

**Comment by CodeName-Anti** [comment]
I fixed the Window glitching.
