### ISSUE TITLE
cheat is great rn

### ISSUE THREAD

**Issue by ZellsAlpha** [CodeName-Anti/CrabGame-Cheat#18]
all i could think about adding is a toggle for the tracers because they are hideous and no one like tracers, and also maybe add some sort of 3D render, maybe a box for players? would be useful in the dorm game when lights are off.

I also know CGHM has a red light green light bot which is just a SimpleY

**Comment by iHunter69** [comment]
> all i could think about adding is a toggle for the tracers because they are hideous and no one like tracers, and also maybe add some sort of 3D render, maybe a box for players? would be useful in the dorm game when lights are off.
> 
> I also know CGHM has a red light green light bot which is just a SimpleY

agreed, we might need stronger punches, but its perfect now.

**Comment by ZellsAlpha** [comment]
> > all i could think about adding is a toggle for the tracers because they are hideous and no one like tracers, and also maybe add some sort of 3D render, maybe a box for players? would be useful in the dorm game when lights are off.
> > I also know CGHM has a red light green light bot which is just a SimpleY
> 
> agreed, we might need stronger punches, but its perfect now.

yes that is very true, the infinite punch doesn't seem to do anything, if anything it makes the punches weaker? or its just a placebo and u cant really infinite punch to gain more knockback on people, no clue

**Comment by Jezzkis** [comment]
> > > all i could think about adding is a toggle for the tracers because they are hideous and no one like tracers, and also maybe add some sort of 3D render, maybe a box for players? would be useful in the dorm game when lights are off.
> > > I also know CGHM has a red light green light bot which is just a SimpleY
> > 
> > 
> > agreed, we might need stronger punches, but its perfect now.
> 
> yes that is very true, the infinite punch doesn't seem to do anything, if anything it makes the punches weaker? or its just a placebo and u cant really infinite punch to gain more knockback on people, no clue

for me it works well, i can push others a lot more and it looks legit
