### ISSUE TITLE
how do i open hack?

### ISSUE THREAD

**Issue by TLGAsh357** [CodeName-Anti/CrabGame-Cheat#20]

**Comment by CodeName-Anti** [comment]
It literally tells it to you in a **bold** font that it is right shift.

**Comment by TLGAsh357** [comment]
i tried it it dosent work

**Comment by TLGAsh357** [comment]
the cheat aint even popping up

**Comment by CodeName-Anti** [comment]
make sure that you have the right version of bepinex. Or just try using the installer and remember to disable your antivirus.

**Comment by TLGAsh357** [comment]
k 1 sec

**Comment by TLGAsh357** [comment]
no it dosent seem to work i closed all my anti viruses and then used installer and i loaded into the game and im pressing r shift and not working?

**Comment by TLGAsh357** [comment]
i got it to wrok
