### ISSUE TITLE
how do you update it?

### ISSUE THREAD

**Issue by HertZxD** [CodeName-Anti/CrabGame-Cheat#23]
i kinda new on unity hack games, could u tell me how do you know the methods like the Instance, GameManager, or the PunchPlayer

when i look on dnspy, i only see obfuscated name

**Comment by eacbypass** [comment]
I just updated it. I might make a pull request with an updated version + a few extra features. btw I would recommend learning gh game hacking bible

**Comment by HertZxD** [comment]
I just updated it, but the game just get updated again, im pissed rn 😅

Pada tanggal Jum, 10 Des 2021 05.37, EAC Bypass ***@***.***>
menulis:

**Comment by eacbypass** [comment]
HertZxD if you just updated it I would recommend telling others how to also update it since I guarantee there finna be way issues

**Comment by eacbypass** [comment]
also for anyone reading this, if you wanna update it try using the LibCopy.cmd :)

**Comment by HertZxD** [comment]
> HertZxD if you just updated it I would recommend telling others how to also update it since I guarantee there finna be way issues

actually i just compile it with new lib, then an error pop up, it say like "Monobehavior bla bla" not defined, so i search a new one with dnspy (i drag asembly-csharp.dll from libary folder) then i search like frozen(cuz i see it has frozen variable on it) then i found it, i just replace the old one with new one
sorry for my bad english :)

**Comment by CodeName-Anti** [comment]
I have an old version of the assembly-csharp.dll, I usually search for field names so I just use dotpeek and open both DLLs, the new one and the old one. I just paste the field name in dotpeek.

**Comment by CodeName-Anti** [comment]
> > HertZxD if you just updated it I would recommend telling others how to also update it since I guarantee there finna be way issues
> 
> actually i just compile it with new lib, then an error pop up, it say like "Monobehavior bla bla" not defined, so i search a new one with dnspy (i drag asembly-csharp.dll from libary folder) then i search like frozen(cuz i see it has frozen variable on it) then i found it, i just replace the old one with new one
> sorry for my bad english :)
> 
> ![image](https://user-images.githubusercontent.com/53701922/145499810-b763babc-b1a8-4017-b7ea-d89de47025f9.png)
> 

Also you cannot edit the assembly-csharp.dll you have to use Bepinex plugins.

**Comment by HertZxD** [comment]
> > > HertZxD if you just updated it I would recommend telling others how to also update it since I guarantee there finna be way issues
> > 
> > 
> > actually i just compile it with new lib, then an error pop up, it say like "Monobehavior bla bla" not defined, so i search a new one with dnspy (i drag asembly-csharp.dll from libary folder) then i search like frozen(cuz i see it has frozen variable on it) then i found it, i just replace the old one with new one
> > sorry for my bad english :)
> > ![image](https://user-images.githubusercontent.com/53701922/145499810-b763babc-b1a8-4017-b7ea-d89de47025f9.png)
> 
> Also you cannot edit the assembly-csharp.dll you have to use Bepinex plugins.

yes i use bepinex, i use dnspy for searching a Class or method on that game


also, do you know how to send a punch to other player?
