### ISSUE TITLE
Insta-Ban

### ISSUE THREAD

**Issue by rjwilder1** [CodeName-Anti/CrabGame-Cheat#24]
Was instantly banned by client side. Server names don't pop up and not able to join servers through lobby code

**Comment by CodeName-Anti** [comment]
Restart your game and steam.

**Comment by rjwilder1** [comment]
I did, I even uninstalled via Geek Uninstaller to clear traces as well.

**Comment by CodeName-Anti** [comment]
This doesnt seem to be an issue of the cheat. It works fine for me and my friends.
