### ISSUE TITLE
How to send a punch to other player (not an issue btw)

### ISSUE THREAD

**Issue by HertZxD** [CodeName-Anti/CrabGame-Cheat#25]
do you know how to send a punch to other player?

also, do you know how to teleport to other player that like server sided (i saw a cheat like break all glass the player instantly teleport to the "Solid" Gameobject and u can't see them)

**Comment by CodeName-Anti** [comment]
just look through the ClientSend methods to send a punch. Add me on discord if you want an old version of crab game. JNNJ#3480
