### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Namespace1** [CodeName-Anti/CrabGame-Cheat#26]
![error](https://user-images.githubusercontent.com/95909445/145552779-2fa706b3-ee12-45ee-8eba-c9549578f2fa.png)
Any idea how to fix this?

**Comment by CodeName-Anti** [comment]
I dont have any idea lol, this seems to be a very big issue on your side.

**Comment by eacbypass** [comment]
Add all the libs with nuget

**Comment by iHunter69** [comment]
> ![error](https://user-images.githubusercontent.com/95909445/145552779-2fa706b3-ee12-45ee-8eba-c9549578f2fa.png) Any idea how to fix this?

looks like even IT pros cant fix this lol

**Comment by Namespace1** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/95909445/145662524-35e05d7b-1183-4fd5-a77b-96e8d0d86187.png)

Now I get this lol I had to reinstall VS 2019

**Comment by CodeName-Anti** [comment]
do you have to .net framework version 4.7.2 installed? If you dont have it download it

**Comment by Namespace1** [comment]
![Screenshot_12](https://user-images.githubusercontent.com/95909445/145703634-da20187a-ab01-4831-9839-7ce426a8f35a.png)
I sure do!

**Comment by CodeName-Anti** [comment]
This should be an error on your side. I'm closing this issue because this isn't an error of this project.
