### ISSUE TITLE
Can't Join servers using those cheats

### ISSUE THREAD

**Issue by Moshikot3** [CodeName-Anti/CrabGame-Cheat#27]
Hi, When those cheats are installed.

I can't join some servers even when i join directly with steam.

I able to join few servers and it might be because the server owner using those cheats too.

**Comment by CodeName-Anti** [comment]
this is not an issue of the cheat. I do **NOT** change anything that has to do with the servers.

**Comment by Moshikot3** [comment]
I tested if few times, You can test it yourself.
This is a real scenario

**Comment by CodeName-Anti** [comment]
wdym by this is a real scenario, it works fine for me and most of my friends

**Comment by CodeName-Anti** [comment]
I'm so sorry this is an issues of the game. I'll try to fix it as soon as possible
