### ISSUE TITLE
Only unsecured lobbies available 

### ISSUE THREAD

**Issue by ANTFOR7717** [CodeName-Anti/CrabGame-Cheat#29]
The new update works successfully with the game, but a issue that was difficult to spot is **if BepInEx or apparently melon-loader is found in the game directory** during loading you will be forced to seeing only unsecured lobbies where there's virtually no full lobbies (Technically putting all cheaters in the same servers). I only know on a high level of this issue's existence and don't know if there's an implementation that can be done to have a workaround. But if there was anyone who was wondering why there is so few lobbies now, this is currently the reason.

**Comment by CodeName-Anti** [comment]
I literally fixed this in the latest version, I patched the checks for it and it works.

**Comment by ANTFOR7717** [comment]
@CodeName-Anti Huge oversight on my part mate, apologies. I was too pre-emptive with my assumptions before even installing the new plugin.

**Comment by CodeName-Anti** [comment]
No problem man, all good.
