### ISSUE TITLE
still not working

### ISSUE THREAD

**Issue by iHunter69** [CodeName-Anti/CrabGame-Cheat#3]
hello, i noticed theres an update, i still dont see ant type of change, when i load it, it shows cheat by JNNJ, but when im in a server and press R-SHIFT it doesnt do anything, but it is loaded though, maybe add a button when we open pause menu we see it.

**Comment by CodeName-Anti** [comment]
Can you send me the LogOutput file? It is located at your CrabGame Folder -> BepInEx -> LogOutput.log

**Comment by iHunter69** [comment]
> Can you send me the LogOutput file? It is located at your CrabGame Folder -> BepInEx -> LogOutput.log

[Message: Preloader] BepInEx 6.0.0-be.521 - Crab Game
[Message: Preloader] BLEEDING EDGE Build #521 from 8e9f1f359271e9052c801cdc10cabb45cacb06c0 at master
[Info   :   BepInEx] System platform: Bits64, Windows
[Info   : Preloader] Running under Unity v2020.3.21
[Info   : Preloader] Detected outdated proxy assemblies, will regenerate them now
[Message: Preloader] Downloading unity base libraries
[Message: Preloader] Extracting downloaded unity base libraries
[Message: Preloader] Generating Il2CppUnhollower assemblies
[Info   : Preloader] Generating Il2CppDumper intermediate assemblies
[Info   :Il2CppDumper] Total time: 00:00:06.3443095
[Info   : Preloader] Executing Il2CppUnhollower generator
[Info   :Unhollower] Reading assemblies...
[Info   :Unhollower] Done in 00:00:00.0040248
[Info   :Unhollower] Reading system assemblies...
[Info   :Unhollower] Done in 00:00:00.0351570
[Info   :Unhollower] Reading unity assemblies...
[Info   :Unhollower] Done in 00:00:00.0146448
[Info   :Unhollower] Creating rewrite assemblies...
[Info   :Unhollower] Done in 00:00:00.0083257
[Info   :Unhollower] Computing renames...
[Info   :Unhollower] Done in 00:00:00.0510103
[Info   :Unhollower] Creating typedefs...
[Info   :Unhollower] Done in 00:00:00.0171408
[Info   :Unhollower] Computing struct blittability...
[Info   :Unhollower] Done in 00:00:00.0018089
[Info   :Unhollower] Filling typedefs...
[Info   :Unhollower] Done in 00:00:00.0067297
[Info   :Unhollower] Filling generic constraints...
[Info   :Unhollower] Done in 00:00:00.0009322
[Info   :Unhollower] Creating members...
[Info   :Unhollower] Done in 00:00:00.2514861
[Info   :Unhollower] Scanning method cross-references...
[Info   :Unhollower] Done in 00:00:00.4404389
[Info   :Unhollower] Finalizing method declarations...
[Info   :Unhollower] Done in 00:00:00.9827537
[Info   :Unhollower] 22600 total potentially dead methods
[Info   :Unhollower] Filling method parameters...
[Info   :Unhollower] Done in 00:00:00.1298154
[Info   :Unhollower] Creating static constructors...
[Info   :Unhollower] Done in 00:00:00.1333482
[Info   :Unhollower] Creating value type fields...
[Info   :Unhollower] Done in 00:00:00.0314564
[Info   :Unhollower] Creating enums...
[Info   :Unhollower] Done in 00:00:00.0097783
[Info   :Unhollower] Creating IntPtr constructors...
[Info   :Unhollower] Done in 00:00:00.0077102
[Info   :Unhollower] Creating type getters...
[Info   :Unhollower] Done in 00:00:00.0186722
[Info   :Unhollower] Creating non-blittable struct constructors...
[Info   :Unhollower] Done in 00:00:00.0079121
[Info   :Unhollower] Creating generic method static constructors...
[Info   :Unhollower] Done in 00:00:00.0058231
[Info   :Unhollower] Creating field accessors...
[Info   :Unhollower] Done in 00:00:00.2232403
[Info   :Unhollower] Filling methods...
[Info   :Unhollower] Done in 00:00:00.6929842
[Info   :Unhollower] Generating implicit conversions...
[Info   :Unhollower] Done in 00:00:00.0061342
[Info   :Unhollower] Creating properties...
[Info   :Unhollower] Done in 00:00:00.0139886
[Info   :Unhollower] Unstripping types...
[Info   :Unhollower] Done in 00:00:00.0268495
[Info   :Unhollower] Unstripping fields...
[Info   :Unhollower] 
[Info   :Unhollower] 720 fields restored
[Info   :Unhollower] 33 fields failed to restore
[Info   :Unhollower] Done in 00:00:00.0090868
[Info   :Unhollower] Unstripping methods...
[Info   :Unhollower] 
[Info   :Unhollower] 17141 methods restored
[Info   :Unhollower] 1382 methods failed to restore
[Info   :Unhollower] Done in 00:00:00.5109834
[Info   :Unhollower] Unstripping method bodies...
[Info   :Unhollower] 
[Info   :Unhollower] IL unstrip statistics: 7776 successful, 3264 failed
[Info   :Unhollower] Done in 00:00:00.4271909
[Info   :Unhollower] Generating forwarded types...
[Info   :Unhollower] Done in 00:00:00.0081591
[Info   :Unhollower] Writing xref cache...
[Info   :Unhollower] Done in 00:00:00.2361991
[Info   :Unhollower] Writing assemblies...
[Info   :Unhollower] Done in 00:00:01.2252139
[Info   :Unhollower] Writing method pointer map...
[Info   :Unhollower] Done in 00:00:00.0487835
[Info   :Unhollower] Done!
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :Unhollower] Registered mono type UnhollowerRuntimeLib.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [CrabGame Cheat 1.6.7]
[Warning:Unhollower] Method System.Collections.Generic.List`1[UnityEngine.Vector3] SmoothNormals(UnityEngine.Mesh) on type JNNJMods.Render.Outline has unsupported return type System.Collections.Generic.List`1[UnityEngine.Vector3]
[Info   :Unhollower] Registered mono type JNNJMods.Render.Outline in il2cpp domain
[Message:CrabGame Cheat] Loaded CrabGame Cheat 1.6.7.5 by JNNJ!
[Message:CrabGame Cheat] Class: MonoBehaviourPublicDi2UIObacspDi2UIObUnique Method: PunchPlayer
[Message:CrabGame Cheat] Class: MonoBehaviourPublicObcumaObInplInObUnique Method: DamagePlayer
[Message:CrabGame Cheat] Class: MonoBehaviourPublicGaprLi1ObGaprInUnique Method: NewPrompt
[Info   :Unhollower] Registered mono type JNNJMods.CrabGameCheat.Loader.BepInExLoader+CheatObject in il2cpp domain
[Message:   BepInEx] Chainloader startup complete
[Message:CrabGame Cheat] Killing GameObject in 30 seconds

**Comment by iHunter69** [comment]
> Can you send me the LogOutput file? It is located at your CrabGame Folder -> BepInEx -> LogOutput.log

also, i did as the installation said, anything outside of it, idk.

**Comment by jesramos** [comment]
when I install BepInEx the servers don't appear

**Comment by iHunter69** [comment]
> when I install BepInEx the servers don't appear

u need to keep restarting till it works

**Comment by jesramos** [comment]
> hello, i noticed theres an update, i still dont see ant type of change, when i load it, it shows cheat by JNNJ, but when im in a server and press R-SHIFT it doesnt do anything, but it is loaded though, maybe add a button when we open pause menu we see it.

same here

**Comment by jesramos** [comment]
[LogOutput.log](https://github.com/CodeName-Anti/CrabGame-Cheat/files/7645639/LogOutput.log)

**Comment by iHunter69** [comment]
> > hello, i noticed theres an update, i still dont see ant type of change, when i load it, it shows cheat by JNNJ, but when im in a server and press R-SHIFT it doesnt do anything, but it is loaded though, maybe add a button when we open pause menu we see it.
> 
> same here

exactly, i asked him to add the script or GUI menu when pausing the game.

**Comment by CodeName-Anti** [comment]
It's not R + Shift, there's another shift button on the right side of your keyboard.

**Comment by jesramos** [comment]
I try and still not dont work

Em sex, 3 de dez de 2021 02:57, CodeName-Anti ***@***.***>
escreveu:

**Comment by iHunter69** [comment]
> It's not R + Shift, there's another shift button on the right side of your keyboard.

still not working

**Comment by CodeName-Anti** [comment]
> > It's not R + Shift, there's another shift button on the right side of your keyboard.
> 
> still not working

It wasn't working because the Cheat wasn't updated for the newest version. I updated the Cheat, try again.

**Comment by jesramos** [comment]
> > > It's not R + Shift, there's another shift button on the right side of your keyboard.
> > 
> > 
> > still not working
> 
> It wasn't working because the Cheat wasn't updated for the newest version. I updated the Cheat, try again.

Working Tks

**Comment by iHunter69** [comment]
> > > It's not R + Shift, there's another shift button on the right side of your keyboard.
> > 
> > 
> > still not working
> 
> It wasn't working because the Cheat wasn't updated for the newest version. I updated the Cheat, try again.

working now phew
