### ISSUE TITLE
Can you get banned

### ISSUE THREAD

**Issue by luam2007** [CodeName-Anti/CrabGame-Cheat#31]
Hey, I know this is a dumb question but does Crab Game have an anti-cheat or anything like that? Like if I do get banned, is it just a straight-up perm ban or just a kick. Also is there a cleaner or anything to remove tracers etc. Thanks

**Comment by CodeName-Anti** [comment]
CrabGame has an anticheat, but it only kicks you out of the current lobby. If you want to removed tracers you will have to edit the source.

**Comment by luam2007** [comment]
So each time i get kicked i can just join another lobby and continue cheating or playing legit?

**Comment by luam2007** [comment]
Or would i get kicked again

**Comment by CodeName-Anti** [comment]
> So each time i get kicked i can just join another lobby and continue cheating or playing legit?

I have disabled the AntiCheat with code. You can still get kicked/banned by the Lobby owner. If you get kicked or banned just go in a new lobby.

**Comment by luam2007** [comment]
How do you uninstall it

**Comment by CodeName-Anti** [comment]
Delete the game folder and reinstall the game.
