### ISSUE TITLE
Lag Issue

### ISSUE THREAD

**Issue by Fabian678909** [CodeName-Anti/CrabGame-Cheat#35]
Works great for 1-2 hours, then turns to 1 frame no matter the graphic settings or player count, even if hacks are turned off.

**Comment by CodeName-Anti** [comment]
There's nothing that should break overtime, can you send the LogOutput.log?

**Comment by iHunter69** [comment]
> There's nothing that should break overtime, can you send the LogOutput.log?

can we spawn weapons next update?

**Comment by Fabian678909** [comment]
dont know what that is. the problem occurs during hat king on any map and repeats itself regardless of the gamemode/map afterwards on EVERY GAME. probs a virus

**Comment by CodeName-Anti** [comment]
Maybe try updating your graphics drivers, or your drivers in general
