### ISSUE TITLE
Installer not working.

### ISSUE THREAD

**Issue by bellboy1** [CodeName-Anti/CrabGame-Cheat#36]
I had the hacks installed before but I had to delete/reinstall Crab Game due to bugs then had to reinstall these hacks but no longer works. I have changed accounts and that's all that is different. The error message is attached.
![Screenshot 2022-01-26 233209](https://user-images.githubusercontent.com/98152208/151163656-a73b79dc-eaac-4220-ba75-ed3cdc146d71.png)

**Comment by bellboy1** [comment]
> You could try to install it manually, [here](https://github.com/CodeName-Anti/CrabGame-Cheat#manual-installation) is a link for it.

When clicking on the lastest BepInEx build link I get the same 502 Bad Gateway error message, could this be on my end?

**Comment by CodeName-Anti** [comment]
Oh yea I forgot, the BepisBuild server is currently down, I will attach the newest version of BepInEx
[BepInEx_UnityIL2CPP_x64_a02c330_6.0.0-be.541.zip](https://github.com/CodeName-Anti/CrabGame-Cheat/files/7943299/BepInEx_UnityIL2CPP_x64_a02c330_6.0.0-be.541.zip).
