### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by orcun9988** [CodeName-Anti/CrabGame-Cheat#37]
While the installer works for me, it doesn't work for my friend. My friend click on the application and nothing opens. what is the reason of this? What software should Him to download? Like net framework 4.8 , c++ runtime , net sdk 5.0 etc idk

**Comment by orcun9988** [comment]
As a second question, antiviruses like windows defender and similar detect the application as a virus, including chrome, is there a way to prevent it? this is not a virus.

**Comment by CodeName-Anti** [comment]
Sometimes the installer doesnt want to open, could be because of FlatUI. Anyways it .NET 4.8 should be enough to run it. There's no way to prevent the virus detection, but you can always use manual installation.
