### ISSUE TITLE
Very nice thing 

### ISSUE THREAD

**Issue by Mikid111** [CodeName-Anti/CrabGame-Cheat#38]
I would be greatful if u will make an option to turn it off
![image](https://user-images.githubusercontent.com/98750864/151798627-69548756-955d-4c05-bd45-bd00170aee36.png)

**Comment by CodeName-Anti** [comment]
No I will not. You could make it yourself, you just need to comment out a single line of code....

**Comment by Mikid111** [comment]
okay so im waiting for more fun stuff :D
