### ISSUE TITLE
How do I remove the colored "CrabGame Cheat..." text on the top?

### ISSUE THREAD

**Issue by 0ember1** [CodeName-Anti/CrabGame-Cheat#39]
![изображение](https://user-images.githubusercontent.com/71174607/152288585-0f1cd99d-f80e-4fd3-86ba-944c0af3f49f.png)

**Comment by CodeName-Anti** [comment]
I will not remove the watermark. You could do it yourself tho, you just need to comment out a single line of code....

**Comment by 0ember1** [comment]
> I will not remove the watermark. You could do it yourself tho, you just need to comment out a single line of code....

I tried removing the line (23172 if I'm not mistaken) that contained the text and it broke the cheat, so it couldn't open the menu

**Comment by CodeName-Anti** [comment]
Well that's because it is not the proper way to edit it. Either you use a tool like dnSpy to edit the binary or you edit the source code which is right here in this repo and compile it yourself.

**Comment by 0ember1** [comment]
> Well that's because it is not the proper way to edit it. Either you use a tool like dnSpy to edit the binary or you edit the source code which is right here in this repo and compile it yourself.

I with dnSpy I tried to just delete these lines but after saving and replacing the dll the menu just doesn't work
