### ISSUE TITLE
How did u find the right method?

### ISSUE THREAD

**Issue by orcun9988** [CodeName-Anti/CrabGame-Cheat#43]
Hello sir, I wonder how do you find the bepinexdetector method?

I'm also love coding mods for example phasmophobia have too bepinex melonloader detections methods too but I can't find the right method in dnspy

**Comment by orcun9988** [comment]
I mean
https://github.com/CodeName-Anti/CrabGame-Cheat/blob/master/CrabGame%20Cheat/Patches/BepInExDetectionPatch.cs

line 10-15   method string
Method_Private_Void_GameObject_Boolean_Vector3_Quaternion_0   how do u know  this method prevents melonlader-bepinex etc

**Comment by orcun9988** [comment]
![image](https://user-images.githubusercontent.com/58307867/176663883-2c359369-b345-431b-98df-f4bbd790cf68.png)
1-) I installed ghidra
2-) I put gameassembly.dll to ghidra then wait 1-2hour to finished decompile
3-) I  go file -> parse c source-> add il2cpp.h ( got from Il2CppInspector ) then set parse options = "-D_GHIDRA_"  then I press Parse to program  then wait 10mins finished
4-) Opened script manager added il2cpp.py (got from Il2CppInspector ) then run waitied 30mins finished all done

now as u said I searched that names "MelonLoader", "BepInEx" , "winhttp.dll"   but it gives me no result

I already know that method is detection void but when look in there is no string  melonloader - bepinex - winhttp.dll-  version.dll - plugins etc what can i do ?

**Comment by CodeName-Anti** [comment]
Well you have to actually use a string search and not search in the method names because they're encrypted. Just google how to do it, I do not have enough experience in Ghidra so I cannot tell you how to do it.
