### ISSUE TITLE
Not loading plugin

### ISSUE THREAD

**Issue by cb12438** [CodeName-Anti/CrabGame-Cheat#45]
When i launch the game it does not load it

**Comment by CodeName-Anti** [comment]
Fixed the installation instructions, please completely uninstall BepInEx by removing the following things:

- dotnet (Folder)
- BepInEx (Folder)
- winhttp.dll (File)
- doorstop_config.ini (File)
- changelog.txt (File)
- .doorstop_version (File)

After removing BepInEx try using the updated instructions for manual installation.

**Comment by cb12438** [comment]
Done of that was it i tried that be for i made this ticket i found out its cause i was using a newer versions of beplnex instead of the version that was in the screenshot
