### ISSUE TITLE
Crab Game decompiled

### ISSUE THREAD

**Issue by raulseixasbr** [CodeName-Anti/CrabGame-Cheat#46]
Hi!
Is there any chance of decompiling the full game?

**Comment by CodeName-Anti** [comment]
Yes there is a way. Either you use Disassembly tools like IDA or Ghidra to disassemble the native il2cpp or you could try using CPP2IL which might help you on some functions with pseudo code.

**Comment by raulseixasbr** [comment]
I decompiled the OSX version which is Mono, but it is obfuscated with beebyte... Don't know how to make that "readable"

**Comment by CodeName-Anti** [comment]
You can't really make it fully readable. You'll have to use an old version of the game where beebyte wanst applied yet and figure out which methods/classes are similar. I recommend use UnityExplorer for that.

**Comment by raulseixasbr** [comment]
Yea... I'm trying that. The problem is that the only version i found on steam depot that wasnt obfuscated, didn't have any levels. Only MainMenu
