### ISSUE TITLE
for the developer

### ISSUE THREAD

**Issue by GZMOSV** [CodeName-Anti/CrabGame-Cheat#48]
sorry to make a issue but why did you came back to this project and started updating it again? I saw you in a lobby and recognized your name and then I realize you started updating it again, but I’m wondering why since the game doesn’t get updates and only has a small community still playing

**Comment by CodeName-Anti** [comment]
I was bored. Also the game had its most players of all time peak 8 days ago ([steamdb](https://steamdb.info/app/1782210/charts/)).
