### ISSUE TITLE
there are no pages for crabcheat installer and dll version

### ISSUE THREAD

**Issue by Lovaq** [CodeName-Anti/CrabGame-Cheat#49]
when you try to follow the link it doesn't exist

![изображение](https://github.com/CodeName-Anti/CrabGame-Cheat/assets/98382972/ddb23ad2-f230-42ff-a5bd-381ab5b73b26)
![изображение](https://github.com/CodeName-Anti/CrabGame-Cheat/assets/98382972/8fc1ab71-8bc6-45db-a78e-0d42ed70be90)

**Comment by CodeName-Anti** [comment]
Thank you for bringing this to my attention. I have fixed the download links in this commit: 51bd22ac18d3deede36a70066bc2db1a17843a68.
