### ISSUE TITLE
Improvements are necessary

### ISSUE THREAD

**Issue by Python840** [CodeName-Anti/CrabGame-Cheat#50]
Some features are breaking the cheat:
- Can't join servers at times or takes very long time to join
- Weapon spawner not working when not a host
- Multiplier punch barely works
- Causes ping issues

If the above are fixed, then it will become perfect as it is. I think I may contribute.

**Comment by CodeName-Anti** [comment]
You're more than welcome to contribute as I probably won't fix those issues.

**Comment by Python840** [comment]
> You're more than welcome to contribute as I probably won't fix those issues.

Thanks, can I also post my own "Modified" version of this cheat? I'll credit you as the original modder.

**Comment by CodeName-Anti** [comment]
Sure, as long as you stick to the license.

**Comment by Donyas7** [comment]
> > You're more than welcome to contribute as I probably won't fix those issues.
> 
> Thanks, can I also post my own "Modified" version of this cheat? I'll credit you as the original modder.

did you ever even make it?
