### ISSUE TITLE
Amazing software design

### ISSUE THREAD

**Issue by W-i-n-7** [CodeName-Anti/CrabGame-Cheat#54]
i was going to test the mod opent the installer and clicked install
without any question or even a warning it permanently deleted all of my plugins and their configs without a backup

**Comment by CodeName-Anti** [comment]
Hello, this mod is not designed to be used while other mods are installed. It also uses a bleeding edge version of BepInEx where as previous versions used the pre.1 version of BepInEx. The installer deletes the pre.1 if installed when you click install.

**Comment by CodeName-Anti** [comment]
Okay I added a message to clear up any confusion while installing.

**Comment by W-i-n-7** [comment]
ty
