### ISSUE TITLE
Glass Breaker 

### ISSUE THREAD

**Issue by Jezzkis** [CodeName-Anti/CrabGame-Cheat#6]
how the glass breaker works, it's breaking them all, but just for me.

**Comment by CodeName-Anti** [comment]
Yea ik thats an issue but im too lazy to fix it.

**Comment by iHunter69** [comment]
> Yea ik thats an issue but im too lazy to fix it.

we need these features:
Respawn after death
More map controls such as time, the buttons which one explodes, red light on and off on our choice etc.
Get all items like inventory changer.

these are all my suggestions

**Comment by iHunter69** [comment]
> Yea ik thats an issue but im too lazy to fix it.

can u add inventory changer?

**Comment by CodeName-Anti** [comment]
> > Yea ik thats an issue but im too lazy to fix it.
> 
> we need these features:
> Respawn after death
> More map controls such as time, the buttons which one explodes, red light on and off on our choice etc.
> Get all items like inventory changer.
> 
> these are all my suggestions
> 

Most of this stuff is just not possible.

**Comment by CodeName-Anti** [comment]
Closed because I fixed glassbreaker in 1.6.8
