### ISSUE TITLE
2 ffixes

### ISSUE THREAD

**Issue by ZellsAlpha** [CodeName-Anti/CrabGame-Cheat#8]
revert the airjump cause its blatent now

and fix glassbreaker cause is broken

add aimbot/triggerbot binds

fix speed slider

**Comment by ZellsAlpha** [comment]
revert the airjump cause its blatent now

and fix glassbreaker cause is broken

add aimbot/triggerbot binds

fix speed slider

**Comment by CodeName-Anti** [comment]
What do you mean by "fix speed slider"?
